kind: pipeline
type: docker
name: baseline

environment:
  DOCKER_BUILDKIT: 1

steps:
  # Parallel test and build steps for faster CI/CD
  - name: test-api
    image: oven/bun:1
    commands:
      - cd api
      - bun install
      - bun test
    failure: ignore
    when:
      event:
        - push
        - pull_request

  - name: test-ui
    image: node:20-alpine
    commands:
      - cd ui
      - npm ci
      - npm run lint
      - npm run type-check
      - npm run test:coverage
    failure: ignore
    when:
      event:
        - push
        - pull_request

  - name: build-api
    image: plugins/docker
    environment:
      DOCKER_HOST: tcp://docker:2375
    settings:
      repo: registry.aqueous.network/baseline-api
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}
        - latest
      dockerfile: api/Dockerfile
      context: api
      target: production
      build_args:
        - NODE_ENV=production
      insecure: true
    when:
      event:
        - push
      branch:
        - main
        - develop

  - name: build-ui
    image: plugins/docker
    environment:
      DOCKER_HOST: tcp://docker:2375
    settings:
      repo: registry.aqueous.network/baseline-ui
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}
        - latest
      dockerfile: ui/Dockerfile
      context: ui
      target: production
      build_args:
        - NODE_ENV=production
      insecure: true
    when:
      event:
        - push
      branch:
        - main
        - develop

  - name: deploy-staging
    image: curlimages/curl
    depends_on:
      - build-api
      - build-ui
    commands:
      - |
        curl -X POST "${PORTAINER_URL}/api/stacks/${PORTAINER_STACK_ID_STAGING}/git/redeploy" \
          -H "X-API-Key: ${PORTAINER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{
            "repositoryReferenceName": "refs/heads/develop",
            "repositoryAuthentication": false
          }'
    when:
      event:
        - push
      branch:
        - develop

  - name: deploy-production
    image: curlimages/curl
    depends_on:
      - build-api
      - build-ui
    commands:
      - |
        curl -X POST "${PORTAINER_URL}/api/stacks/${PORTAINER_STACK_ID_PRODUCTION}/git/redeploy" \
          -H "X-API-Key: ${PORTAINER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{
            "repositoryReferenceName": "refs/heads/main",
            "repositoryAuthentication": false
          }'
    when:
      event:
        - push
      branch:
        - main

  - name: notify-success
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
      username: drone
      template: |
        ✅ *{{repo.name}}* deployment successful
        📦 Branch: `{{build.branch}}`
        🏷️ Tag: `{{build.tag}}`
        👤 Author: {{build.author}}
        🔗 <{{build.link}}|View Build>
    when:
      status:
        - success
      event:
        - push
      branch:
        - main
        - develop

  - name: notify-failure
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
      username: drone
      template: |
        ❌ *{{repo.name}}* deployment failed
        📦 Branch: `{{build.branch}}`
        👤 Author: {{build.author}}
        🔗 <{{build.link}}|View Build>
    when:
      status:
        - failure

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: baseline_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

  - name: redis
    image: redis:7-alpine
    ports:
      - 6379

  - name: docker
    image: docker:20.10.16-dind
    privileged: true
    environment:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
    command:
      - dockerd
      - --host=unix:///var/run/docker.sock
      - --host=tcp://0.0.0.0:2375
      - --insecure-registry=registry.aqueous.network

---
kind: secret
name: slack_webhook
get:
  path: slack
  name: webhook
