kind: pipeline
type: docker
name: baseline

environment:
  DOCKER_BUILDKIT: 1

steps:
  # Parallel test and build steps for faster CI/CD
  - name: test-api
    image: oven/bun:1
    commands:
      - cd api
      - bun install
      - bun test
    failure: ignore
    when:
      event:
        - push
        - pull_request

  - name: test-ui
    image: node:20-alpine
    commands:
      - cd ui
      - npm ci
      - npm run lint
      - npm run type-check
      - npm run test:coverage
    failure: ignore
    when:
      event:
        - push
        - pull_request

  - name: build-api
    image: plugins/docker
    settings:
      repo: registry.aqueous.network/baseline-api
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}
        - latest
      dockerfile: api/Dockerfile
      context: api
      target: production
      build_args:
        - NODE_ENV=production
      insecure: true
    when:
      event:
        - push
      branch:
        - main
        - develop

  - name: build-ui
    image: plugins/docker
    settings:
      repo: registry.aqueous.network/baseline-ui
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}
        - latest
      dockerfile: ui/Dockerfile
      context: ui
      target: production
      build_args:
        - NODE_ENV=production
      insecure: true
    when:
      event:
        - push
      branch:
        - main
        - develop

  - name: deploy-staging
    image: curlimages/curl
    # depends_on:
    #   - build-api
    #   - build-ui
    environment:
      PORTAINER_URL:
        from_secret: PORTAINER_URL
      PORTAINER_API_KEY:
        from_secret: PORTAINER_API_KEY
      PORTAINER_STACK_ID_STAGING:
        from_secret: PORTAINER_STACK_ID_STAGING
    commands:
      - |
        curl -X POST "${PORTAINER_URL}/api/stacks/${PORTAINER_STACK_ID_STAGING}/git/redeploy" \
          -H "X-API-Key: ${PORTAINER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{
            "repositoryReferenceName": "refs/heads/develop",
            "repositoryAuthentication": false
          }'
    when:
      event:
        - push
      branch:
        - develop

  - name: deploy-production
    image: curlimages/curl
    # depends_on:
    #   - build-api
    #   - build-ui
    settings:
      portainer_url:
        from_secret: PORTAINER_URL
      portainer_api_key:
        from_secret: PORTAINER_API_KEY
      portainer_stack_id:
        from_secret: PORTAINER_STACK_ID_PRODUCTION
    commands:
      - |
        echo "=== SECRET ACCESS TEST ==="
        echo "Available environment variables:"
        env | grep -E '^(PLUGIN_|DRONE)' | sort
        echo "=== DEBUG VALUES ==="
        echo "Debug: PLUGIN_PORTAINER_URL=${PLUGIN_PORTAINER_URL}"
        echo "Debug: PLUGIN_PORTAINER_API_KEY length: ${#PLUGIN_PORTAINER_API_KEY}"
        echo "Debug: PLUGIN_PORTAINER_STACK_ID=${PLUGIN_PORTAINER_STACK_ID}"
        curl -X POST "${PLUGIN_PORTAINER_URL}/api/stacks/${PLUGIN_PORTAINER_STACK_ID}/git/redeploy" \
          -H "X-API-Key: ${PLUGIN_PORTAINER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{
            "repositoryReferenceName": "refs/heads/main",
            "repositoryAuthentication": false
          }'
    when:
      event:
        - push
      branch:
        - main

  - name: notify-success
    image: plugins/slack
    depends_on:
      - deploy-staging
      - deploy-production
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
      username: drone
      template: |
        ✅ *{{repo.name}}* deployment successful
        📦 Branch: `{{build.branch}}`
        🏷️ Tag: `{{build.tag}}`
        👤 Author: {{build.author}}
        🔗 <{{build.link}}|View Build>
    when:
      status:
        - success
      event:
        - push
      branch:
        - main
        - develop

  - name: notify-failure
    image: plugins/slack
    depends_on:
      - deploy-staging
      - deploy-production
    settings:
      webhook:
        from_secret: slack_webhook
      channel: deployments
      username: drone
      template: |
        ❌ *{{repo.name}}* deployment failed
        📦 Branch: `{{build.branch}}`
        👤 Author: {{build.author}}
        🔗 <{{build.link}}|View Build>
    when:
      status:
        - failure

services:
  - name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: baseline_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

  - name: redis
    image: redis:7-alpine
    ports:
      - 6379

---
kind: secret
name: slack_webhook
get:
  path: slack
  name: webhook
