version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: baseline-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-baseline}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: baseline-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: baseline-api
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-baseline}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      API_PORT: ${API_PORT:-3000}
      UI_URL: ${UI_URL:-http://localhost:5173}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-}
      OIDC_ROOT_URL: ${OIDC_ROOT_URL:-}
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: baseline-ui
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      API_URL: ${API_URL:-http://api:3000}
      WS_URL: ${WS_URL:-ws://api:3000}
      APP_NAME: ${APP_NAME:-Baseline}
      APP_VERSION: ${APP_VERSION:-1.0.0}
      UI_PORT: ${UI_PORT:-5173}
    ports:
      - "${UI_PORT:-5173}:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
